DEV_README.md, Makefile, imageConfigs/grafana/grafana.ini, imageConfigs/grafana/provisioning/dashboards/dashboard.json, imageConfigs/grafana/provisioning/dashboards/dashboard.yml, imageConfigs/grafana/provisioning/dashboards/docker_metrics.json, imageConfigs/grafana/provisioning/dashboards/k8s-views-nodes.json, imageConfigs/grafana/provisioning/dashboards/snapshot-dashboard.json, imageConfigs/grafana/provisioning/datasources/srcProm.yml, imageConfigs/prometheus/prometheus.yml, morpheus/docker-compose-browser.yaml, morpheus/docker-compose-dev.yaml, morpheus/docker-compose-prod.yaml, morpheus/dockerfile.dev, morpheus/dockerfile.prod
https://osp4.atlassian.net/browse/SCRUM-16
Added docker compose files into project
Added Developer ReadMe file with developer workflower
- [ X] I've followed the [Contributing guidelines](https://github.com/oslabs-beta/.github/blob/main/docs/CONTRIBUTING.md)
- [ X] I've titled my PR according to the [Conventional Commits spec](https://conventionalcommits.org)
- [ X] I've updated documentation (if appropriate)
=> Added docker compose files into project structure

Makefile, morpheus/docker-compose-morpheus.yaml, morpheus/dockerfile.dev
Fixed the container port numbers to start at 50000 and changed Makefile commands to be Morpheus specific
=> Changed port numbers and Makefile commands

README.md, morpheus/docker-compose-morpheus.yaml
Got cAdvisor working with the latest version on Mac
=> Got cAdvisor working with the latest version on Mac

Makefile, morpheus/docker-compose-morpheus-wsl.yaml
Added potential solution for WSL, which uses different volume mappings
=> Added potential solution for WSL, which uses different volume mappings

morpheus/docker-compose-morpheus.yaml, morpheus/dockerfile.dev
Removed CMD from dockerfile.dev and adjusted morpheus.yaml file
=> Removed CMD from dockerfile.dev and adjusted morpheus.yaml file

imageConfigs/grafana/grafana.ini, k8sConfig/manifests/grafana-config.yaml
Updated dashboard date formats to UTC and k8s grafana configuration
=> Updated dashboard date formats to UTC and k8s grafana configuration

imageConfigs/grafana/provisioning/dashboards/additional-system.json, imageConfigs/grafana/provisioning/dashboards/sample.json, nextui/app/components/Header/Header.tsx, nextui/app/kubernetes/Dashboard.tsx, nextui/app/kubernetes/page.tsx, nextui/app/page.tsx, nextui/app/systemData/Dashboard.tsx, nextui/app/systemData/page.tsx, nextui/app/systemData/systemData.module.scss, nextui/tailwind.config.ts
=> UI-system made

.vscode/settings.json, imageConfigs/grafana/grafana.ini, nextui/app/kubernetes/Dashboard.tsx, nextui/app/kubernetes/kubernetes.module.scss, nextui/app/kubernetes/page.tsx
=> First version of k8s dashboard

server/package-lock.json, server/package.json, server/prometheus/client.js, server/routes/index.js, server/server.js
=> Connected backend bedrock and prometheus api call to frontend

imageConfigs/postgres/init_prod.sql, k8sConfig/Makefile, morpheus/docker-compose-morpheus.yaml, morpheus/dockerfile.dev
=> Added postgres container to solution

imageConfigs/postgres/init_prod.sql, nextui/app/api/v1/usersettings/route.ts, nextui/app/dashboard/settings/actions.ts, nextui/app/dashboard/settings/page.tsx, nextui/db/pgModel.ts, nextui/package-lock.json, nextui/package.json
Added postgres DB update for user fname, lname, email
=> Added postgres DB update for user fname, lname, email

nextui/package-lock.json
=> fixed package-lock.json sync issue

nextui/app/docker/containers/Dashboard.tsx, nextui/app/docker/containers/dashboard.css, nextui/app/globals.css, package-lock.json, package.json
=> fixed dashboard ui

nextui/app/components/Header/Header.tsx
Co-authored-by: dariusteng <dariusteng@users.noreply.github.com>
=> Clicking out of the left nav will immediately close it

nextui/app/dashboard/data/page.tsx
=> changed img to nextjs Image for build process bundling

nextui/app/kubernetes/DashboardAichat.tsx, nextui/app/kubernetes/react-graph-vis.d.ts, nextui/package-lock.json, nextui/package.json, nextui/tsconfig.json
=> Added typescript types to DashboardAichat

nextui/app/docker/containers/Dashboard.tsx, nextui/app/docker/containers/dashboard.css
=> change the dashboard to use typescript &materialui

nextui/app/components/Header/Header.tsx, nextui/app/components/sideBar/sideBar.tsx, nextui/app/layout.tsx, nextui/app/page.tsx
=> ui upgrade

nextui/app/components/Header/Header.tsx
=> slight adjustment on Header icon

DEV_README.md, README.md
Added team LinkedIn info
Updated DEV_README with instructions for k8s.
=> Updated DEV_README with instructions for k8s.

nextui/app/docker/containers/Dashboard.tsx
=> fixed a styling anomaly on Docker Dashboard

nextui/app/docker/containers/page.tsx
=> adjusted container page styling

morpheus/scripts/prometheus_to_postgres.py, nextui/app/docker/containers/page.tsx
=> adjusted cpu usage metric in database passing incorrectly

nextui/app/api/db-metrics/route.ts, nextui/app/components/MetricsDisplay.module.css, nextui/app/components/MetricsDisplay.tsx
=> Fixed Database view on /metrics & adjusted styling

morpheus/scripts/prometheus_to_postgres.py, nextui/app/metrics/Dashboard.tsx
=> adjusted Python script metrics & Styling for db metrics dashboard

nextui/app/dashboard/data/page.tsx
=> fixed render error

nextui/__tests__/SystemData.test.tsx
=> SystemData tests

README.md
=> Added website link to README

nextui/tsconfig.json
=> Fixed npm run build issue

DEV_README.md, package-lock.json
=> docs: OpenAI instructions

imageConfigs/postgres/init_prod.sql, morpheus/scripts/prometheus_to_postgres.py, nextui/app/components/MetricsDisplay.tsx
=> database visualization fixes
